version: '3.8'

services:


  postgres:
    image: postgres:16
    container_name: subscription-tracker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_tracker_db


  subscription-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription-tracker-app
    ports:
      - "8090:8080"

